# Generated by Django 5.0.6 on 2024-06-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APM_APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_farmer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_system_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_village_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('village_admin', 'Village Admin'), ('system_admin', 'System Admin')], default='farmer', max_length=20),
            preserve_default=False,
        ),
    ]
