# Generated by Django 5.0.6 on 2024-06-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APM_APP', '0002_remove_user_is_farmer_remove_user_is_system_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='estimated_date',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('village_admin', 'Village Admin'), ('system_admin', 'System Admin')], default='farmer', max_length=15),
        ),
    ]
