# Generated by Django 5.0.6 on 2024-07-11 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APM_APP', '0003_remove_activity_estimated_date_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='duration',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='UnplannedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('description', models.TextField()),
                ('delay_days', models.IntegerField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APM_APP.farmerschedule')),
            ],
        ),
    ]
