# Generated by Django 5.0.6 on 2024-07-12 02:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APM_APP', '0004_activity_duration_unplannedevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmeragriculturalwork',
            name='has_unplanned_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmeragriculturalwork',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 7, 12)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmeragriculturalwork',
            name='unplanned_event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmeragriculturalwork',
            name='unplanned_event_delay_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmeragriculturalwork',
            name='unplanned_event_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='UnplannedEvent',
        ),
    ]
