# Generated by Django 5.0.6 on 2024-07-16 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APM_APP', '0005_farmeragriculturalwork_has_unplanned_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='ID_Activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_activities', to='APM_APP.activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
