# Generated by Django 5.0.6 on 2024-07-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APM_APP', '0007_activity_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='step',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='farmeragriculturalwork',
            name='estimated_harvest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmeragriculturalwork',
            name='estimated_harvest_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
