# Generated by Django 5.0.6 on 2024-07-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APM_APP', '0008_alter_activity_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerschedule',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmerschedule',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
