# Generated by Django 5.0.6 on 2024-07-31 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APM_APP', '0010_remove_activity_id_activity_alter_activity_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='delay_after_dependency',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='dependencies',
            field=models.ManyToManyField(blank=True, to='APM_APP.activity'),
        ),
    ]
