# Generated by Django 5.0.6 on 2024-07-31 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APM_APP', '0011_activity_delay_after_dependency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='delay_after_dependency',
            new_name='parallel_start_delay',
        ),
    ]
