# Generated by Django 5.0.6 on 2024-07-31 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APM_APP', '0012_rename_delay_after_dependency_activity_parallel_start_delay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='dependencies',
        ),
        migrations.AddField(
            model_name='activity',
            name='depends_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_activities', to='APM_APP.activity'),
        ),
    ]
