# Generated by Django 5.0.6 on 2024-07-31 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APM_APP', '0014_remove_activity_depends_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='step',
        ),
        migrations.AddField(
            model_name='activity',
            name='delay_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='reference_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_activities', to='APM_APP.activity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_type',
            field=models.CharField(blank=True, choices=[('start', 'Start of reference activity'), ('end', 'End of reference activity'), ('start_after', 'X days after start of reference activity'), ('end_after', 'X days after end of reference activity')], max_length=20, null=True),
        ),
    ]
