# Generated by Django 5.0.6 on 2024-07-31 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APM_APP', '0016_remove_activity_delay_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='depends_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_activities', to='APM_APP.activity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_after_days',
            field=models.IntegerField(default=0),
        ),
    ]
