# Generated by Django 5.0.6 on 2024-07-31 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APM_APP', '0017_activity_depends_on_activity_start_after_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='step',
        ),
    ]
