# Generated by Django 5.0.6 on 2024-08-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APM_APP', '0018_remove_activity_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='start_after_days',
        ),
        migrations.AddField(
            model_name='activity',
            name='start_after_hours',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='farmeragriculturalwork',
            name='estimated_harvest_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmeragriculturalwork',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
