# Generated by Django 5.0.6 on 2024-08-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APM_APP', '0019_remove_activity_start_after_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='start_after_hours',
        ),
        migrations.AddField(
            model_name='activity',
            name='start_after_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='farmeragriculturalwork',
            name='estimated_harvest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmeragriculturalwork',
            name='start_date',
            field=models.DateField(),
        ),
    ]
