# Generated by Django 5.0.6 on 2024-08-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APM_APP', '0020_remove_activity_start_after_hours_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='start_after_days',
            new_name='start_after_hours',
        ),
        migrations.AlterField(
            model_name='farmeragriculturalwork',
            name='estimated_harvest_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmeragriculturalwork',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
