# Generated by Django 5.0.6 on 2024-08-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APM_APP', '0021_rename_start_after_days_activity_start_after_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='optionnal',
            field=models.BooleanField(default=False),
        ),
    ]
