# Generated by Django 5.0.6 on 2024-08-02 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APM_APP', '0022_activity_optionnal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmeragriculturalwork',
            name='has_unplanned_event',
        ),
        migrations.RemoveField(
            model_name='farmeragriculturalwork',
            name='unplanned_event_date',
        ),
        migrations.RemoveField(
            model_name='farmeragriculturalwork',
            name='unplanned_event_delay_days',
        ),
        migrations.RemoveField(
            model_name='farmeragriculturalwork',
            name='unplanned_event_name',
        ),
    ]
