# Generated by Django 5.0.6 on 2024-08-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APM_APP', '0025_alter_farmerschedule_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerschedule',
            name='activity_data',
            field=models.JSONField(default=dict),
        ),
    ]
