# Generated by Django 5.0.6 on 2024-08-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APM_APP', '0026_alter_farmerschedule_activity_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerschedule',
            name='activity_data',
        ),
        migrations.AddField(
            model_name='farmerschedule',
            name='funds_needed',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerschedule',
            name='human_resources_needed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
